---
fs3combat:
  damage_mods:
    HEAL: 0
    FLESH: 0.25
    MODERATE: 2
    IMPAIR: 4
    INCAP: 7
  damage_table:
    GRAZE: 15
    FLESH: 65
    MODERATE: 100
    IMPAIR: 125
  healing_cron:
    hour:
    - 2
    minute:
    - 47
  healing_points:
    HEAL: 0
    FLESH: 7
    MODERATE: 7
    IMPAIR: 10
    INCAP: 7
  pc_knockout_bonus: 1
