---
login:
  activity_cron:
    minute:
    - 0
  allow_creation: false
  allow_web_registration: false
  blacklist_cron:
    day:
    - 1
    - 15
    hour:
    - 3
    minute:
    - 0
  creation_not_allowed_message: Shattered is not accepting new characters at this time. See the 
    front page for more information.
  guest_disabled_message: Shattered is not accepting new characters at this time. See the 
    front page for more information.
  guest_role: guest
  login_not_allowed_message: Shattered is not accepting new characters at this time. See the 
    front page for more information.
  notice_cleanup_cron:
    day:
    - 18
    hour:
    - 2
    minute:
    - 19
  notice_timeout_days: 60
  portal_requires_registration: false
  shortcuts:
    logout: quit
    con: connect
    newpassword: password/reset
    conn: connect
    kick: boot
    password/change: password/set
    ban/delete: ban/remove
    notice: notices
  permissions:
    login: Able to log in.
    manage_login: Can access login-related admin tools like resetting someone's password.
  random_guest_selection: false
  boot_timeout_seconds: 300
  disable_nonadmin_logins: false
