---
who:
  where_style: scene
  who_fields:
  - field: status
    width: 7
    title: Status
  - field: lookingforrp
    width: 5
    title: RP?
  - field: name
    width: 10
    title: Name
  - field: bonded
    width: 15
    title: Mythic Name
  - field: group
    value: mythic
    width: 12
    title: Mythic
  - field: connected
    width: 7
    title: Conn
  - field: idle
    width: 4
    title: Idle
